config/routes.rb
Rails.application.routes.draw do
  get 'searches/index'
  get 'searches/search'
  
  root "searches#index"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  require 'open-uri'
  require 'json'

  DEVELOPER_KEY = 'AIzaSyDeLSrLhx_8dBSsFPZ9X0gg-G0JDSbITuk'

  def index
  end

  # 参考サイト
  # http://crossfabricate.hatenablog.com/entry/2016/03/28/194203
  def search
    #検索キーワードを取得
    @search_data = params.require(:search_data).permit(:keyword)
    @keyword = @search_data["keyword"]

    #検索処理
    url = "https://www.googleapis.com/youtube/v3/search?part=snippet&q=" + @keyword + "&key=" + DEVELOPER_KEY + "&maxResults=10"
    res = open(url)
    result = res.read
    search_response = JSON.parse(result)
    
    #検索結果
    @search_result = ""
    
    search_response["items"].each do |search_result|
      @search_result += "<tr>"
      @search_result += "<td>" + search_result["id"]["kind"].to_s + "</td>"
      @search_result += "<td>" + search_result["snippet"]["title"].to_s + "</td>"
      @search_result += "<td>" + search_result["id"]["videoId"].to_s + "</td>"
      @search_result += "</tr>"
    end

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>YoutubeApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/searches/index.html.erb
<h1>Searches#index</h1>
<p>Find me in app/views/searches/index.html.erb</p>
 <div class="sky-form" role="form">
    <%= form_for :search_data, url: searches_search_path, method: :get do |f| %>
        <fieldset>
          <section>
            <label class="label">
              <%= f.label :keyword, 'キーワード'  %>
            </label>
            <label class="input state-success">
              <%= f.text_field :keyword %>
            </label>
          </section>
          <%= f.submit '検索' %>
        </fieldset>
    <% end %>
</div>

app/views/searches/search.html.erb
<h1>Searches#search</h1>
<p>Find me in app/views/searches/search.html.erb</p>
<p>キーワード：</p>
<p><%= @keyword %></p>
<p>検索結果：</p>
<table><tbody>
<%= @search_result.html_safe %>
</tbody></table>